### ISSUE TITLE
Wrapping component with ThemeProvider throws error

### ISSUE THREAD

**Issue by ReasonableDeveloper** [smooth-code/smooth-ui#27]
Hey, thank you for this awesome design system.
I'm using styled-components in my app and just added the <ThemeProvider> component to the top of my component tree. When I try to render any smooth-ui component, it fails with the error `TypeError: props.theme[name] is not a function`.
I tried to prevent styled components from passing the prop to the components but the problem still persisted.
```JavaScript
import { Input as UntehmedInput } from 'smooth-ui';
const Input = styled(({ theme, ...rest }) => <UnthemedInput {...rest} />)``;
```

I'm using SSR styled-components with Next.js if this information helps. Below is the stacktrace.
```
TypeError: props.theme[name] is not a function
    at Server\src\node_modules\smooth-ui\dist\smooth-ui.cjs.js:248:29
    at Server\src\node_modules\styled-components\dist\styled-components.cjs.js:207:25
    at Array.reduce (<anonymous>)
    at flatten (Server\src\node_modules\styled-components\dist\styled-components.cjs.js:185:17)
    at ComponentStyle.generateAndInjectStyles (Server\src\node_modules\styled-components\dist\styled-components.cjs.js:2083:21)
    at StyledComponent.generateAndInjectStyles (Server\src\node_modules\styled-components\dist\styled-components.cjs.js:1767:38)
    at Server\src\node_modules\styled-components\dist\styled-components.cjs.js:1799:41
    at subscribe (Server\src\node_modules\styled-components\dist\styled-components.cjs.js:1525:5)
    at StyledComponent.componentWillMount (Server\src\node_modules\styled-components\dist\styled-components.cjs.js:1795:28)
    at processChild (Server\node_modules\react-dom\cjs\react-dom-server.node.development.js:2170:16)
```

**Comment by neoziro** [comment]
Hi! I think you got this error because you use a theme in your application without extending the default theme of Smooth UI. Also you are not using the latest version of Smooth UI. I suggest you to follow the following guides:

- [Getting Started](https://smooth-ui.smooth-code.com/docs-getting-started)
- [Theming](https://smooth-ui.smooth-code.com/docs-basics-theming)

**Comment by ReasonableDeveloper** [comment]
I did not realize I was running an older verison. Thank you 😊
